### ISSUE TITLE
Gør det muligt at slå WSL2 til og fra

### ISSUE THREAD

**Issue by sorenhansendk** [DineroRegnskab/willy#19]
Vi skal have gjort det muligt at slå WSL2 til og fra via 2 simple kommandoer:

- `willy wsl --enable` for at slå det til
- `willy wsl --disable` for at slå det fra

Husk at gør beskeden tydelig omkring at man skal genstarte Docker 🐳

**Comment by Baune8D** [comment]
Done 🙏
