### ISSUE TITLE
Autocompletion på start

### ISSUE THREAD

**Issue by sorenhansendk** [DineroRegnskab/willy#25]
Vi skal have lavet så der er autocompletion på `willy start` så man kan skrive `willy start c` og så trykke tab. Så vil de services der starter med `c` automatisk komme frem.

**Comment by Baune8D** [comment]
Til dels løst i: https://github.com/DineroRegnskab/willy/issues/37 da willy nu foreslår services der indeholder den tekst man har skrevet hvis der ikke kan startes en konkret stack.

Jeg tror ikke vi kan gøre det meget bedre ind det. Autocompletion i terminalen er noget der skal laves for hver enkelt type terminal (bash har fx. et system til at manuelt progremmere completions, men de vil ikke virke i andre terminaler) og er ikke noget der kan laves i node.js eller noget andet cli framework så vidt jeg ved.

**Comment by sorenhansendk** [comment]
Ok, helt fint 👍 Lyder lidt for bøvlet at få lavet, i forhold til den værdi det skaber. Vi lukker her.
