### ISSUE TITLE
Docker får lidt for meget memory

### ISSUE THREAD

**Issue by sorenhansendk** [DineroRegnskab/willy#29]
Vi skal have ændret lidt på vores grænser for hvor meget memory Docker hapser/reserverer.

Lige nu tager den som minimum 16 GB - den skal sættes ned til 10 GB. Der skal også laves et parameter man selv kan kaste efter Willy, f.eks. `willy wsl2 configure --max-memory 12GB`

**Comment by Baune8D** [comment]
Løst i https://github.com/DineroRegnskab/willy/issues/37

**Comment by sorenhansendk** [comment]
Super godt 👍 Jeg kan ikke lige lure på koden om den ender med at udskrive hvor meget den har givet Docker af ressourcer. Hvis den ikke gør det, kan vi så lave så den lige skriver det som en lille note? 😇

**Comment by Baune8D** [comment]
Ja det for jeg lige klemt ind 👍
