### ISSUE TITLE
Release Willy v4.0.0

### ISSUE THREAD

**Issue by Baune8D** [DineroRegnskab/willy#37]
Jeg har givet den fuld gas her op til påsken og det er blevet til ret mange ting. Jeg har desværre ikke lavet PR's da det ville blive problematisk at arbejde effektivt da jeg har pillet ved næsten alle områder af kodebasen og du samtidig har holdt ferie 😄. Men jeg er personligt vanvittig glad for det fundament der nu ligger og de ændringer der er kommet ind.

# CHANGELOG
## Refaktoreringer:
* Services er omskrevet til singleton klasser, giver fx. mulighed for brug af getters og setters samt bedre scoping.
* 90% er RxJS koden er omskrevet og erstattet af async/await promises. Den gamle kodebase var spundet ind i rigtig meget RxJS kode, men da langt størstedelen af kodebasen kører sekventielt, giver det ikke rigtig nogle benefits at bruge observables.Dette har gjort koden både kortere, og lettere at læse. Der er stadig nogle enkelte steder hvor det giver mening stadig at bruge RxJS observables, bl.a. ved parallel opstart af stacks og groups.
* `Stacks`, `groups` og `services` lever nu som klasser med deres egen behaviour, dette gør det meget mere fleksibelt at arbejde med disse.  Fx. kan man nu lave noget i stil med: 
```typescript
const stacks = stackService.getStacks();
stacks.forEach((stack) => stack.start()); // Kører start af alle stacks
stacks.forEach((stack) => stack.restart()); // Genstarter alle stacks
stacks.forEach((stack) => stack.stop()); // Stopper alle stacks
```
* Omdøbning af de fleste interfaces så de bedre reflekterer hvad de bliver brugt til.
* **Udnyt TypeScript fuldt ud! Dette betyder at der nu er type annotations på 100% af kodebasen.**
  * Alle tidligere ESLint regler der var slået fra, er nu genaktiveret og koden er rettet til.
  * TypeScript kører nu i strict mode og koden er rettet til. 
* `willy wsl2` er nu splittet op i subcommands for at understøtte options på de enkelte kommandoer. Således hedder de nu: 
  * `willy wsl2 configure`
  * `willy wsl2 disable`
  * `willy wsl2 install`

## Nye features:
* Genstarter automatisk alle services i en stack via. `docker service update` hvis de allerede kørte i forvejen for at tvinge dem til at opdatere til det nyeste image.
![image](https://user-images.githubusercontent.com/30204280/113573263-14f74e80-961a-11eb-94f0-631b7f600eec.png)
* Hvis man skriver et ugyldigt stack navn prøver willy automatisk at finde et korrekt navn baseret på det der blev specificeret: fx. `willy start dns` starter infrastructure_dns da det er den eneste stack der indeholder ordet 'dns'.
![image](https://user-images.githubusercontent.com/30204280/113573332-3a845800-961a-11eb-8a01-0e13c1eae838.png)
* Hvis man skriver et ugyldigt stack navn som matcher flere stacks, giver willy muligheden for at vælge dem du vil starte fra en checkliste. Fx. `willy start infrastructure` giver en checkliste over alle stacks der indeholder ordet 'infrastructure'. Løser til dels https://github.com/DineroRegnskab/willy/issues/25
![image](https://user-images.githubusercontent.com/30204280/113573403-6273bb80-961a-11eb-9aa1-ae411867296d.png)
**BEMÆRK:** På grund af ugyldige stack navne i `willy-groups.json` bliver man nu spurgt om hvilke services man vil starte når man eksekverer `willy group start workbox`. Se issue https://github.com/DineroRegnskab/dinero-web-2.0/issues/7074
* Hvis der findes flere services under en stack, vil `willy logs <stack>` giver en checkliste over disse services, så man kan vælge den man vil hente logs fra. Dette løser problemet fra før hvor logs kommandoen ville crashe hvis en stack indeholdte flere services.
![image](https://user-images.githubusercontent.com/30204280/113573464-7ae3d600-961a-11eb-9a31-fbd91019d579.png)
* Bedre error reporting hvis services fejler under opstart. Før i tiden hvis man fx. brugte kommandoen `willy group start workbox` ville outputtet til terminalen stoppe efter første fejl og terminalen ville hænge indtil resten var kørt færdig i baggrunden. Nu printer vi alle fejlbeskeder ud efterfulgt af en besked om at stack'en ikke kunne startes.
![image](https://user-images.githubusercontent.com/30204280/113574321-1f1a4c80-961c-11eb-8e8e-dc2f53edd9f2.png)
* Hvis vi detekterer en `dotnet restore` fejl under build, bliver der printet en besked om at du højst sandsynligt skal logge på vpn. Bagved dette ligger et system hvor man nemt kan plugge flere beskeder ind hvis vi detekterer diverse common cases.
![image](https://user-images.githubusercontent.com/30204280/113574352-35280d00-961c-11eb-8651-ed6bc3a10fed.png)
* `--output` option erstattet af `--verbose`. Denne option giver generelt mere information om alt der bliver kørt, den er samtidig blevet tilføjet til markant flere kommandoer så det er en gennemgående feature.
* `--max-memory` option tilføjet til `willy init` og alle `willy wsl2` kommandoer.

## Bugfixes:
* Ram bliver nu kalkuleret således: (Løser: https://github.com/DineroRegnskab/willy/issues/29)
  * Computer <= 32GB ram = 10GB allokeret
  * Computer > 32GB ram = 16GB allokeret
* Fejl besker er blevet gjort mere specifikke i mange tilfælde.
* Alle kommandoer til stacks og grupper er case insensitive nu.

De følgende ting fra https://github.com/DineroRegnskab/dinero-devops/issues/168 er hakket af som konsekvens af dette release:
*  `Willy start` skal ikke være case-sensitive
*  `Willy start $serviceNavn` - giv forslag ved flere services (eks- tagprediction har tagprediction_servce samt tagprediction_benchmark) - her skulle den spørge hvilke der skal startes
*  `Willy log $serviceNavn` starter docker service log --follow --timestamp $serviceNavn

Der er releaset en ny `v4.0.0-alpha2` version som meget gerne må testes af.

Jeg tilføjer nyt til dette issue hvis jeg lige kommer i tanke om andet.

**Comment by sorenhansendk** [comment]
Det lyder rigtig godt! Jeg får opdateret artiklerne i den nye Willy wiki med de nye funktioner. Super godt arbejde 🎉
